name: Deploy demo to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d
      - name: Upload artifact
        uses: actions/upload-pages-artifact@98ef48e41587a300b82de4cf298aa98b57b2faae
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@0a48e98c2a9f5f6f83df7e46e5e61f8d61b6a0e7
        with:
          branch: main
          folder: '.'
